CREATE TABLE Person
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(100) NOT NULL,
    year_of_birth INT          NOT NULL,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    "password"    VARCHAR      NOT NULL,
    "role"        VARCHAR(15)  NOT NULL,
    booking       BOOLEAN      NOT NULL,
    created_at    DATE         NOT NULL
);

CREATE TABLE Book
(
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(100) NOT NULL,
    author         VARCHAR(100) NOT NULL,
    genre          VARCHAR(20)  NOT NULL,
    reserved_until TIMESTAMP,
    taken_at       DATE,
    person_id      INT          REFERENCES Person (id) ON DELETE SET NULL
);


insert into Book (title, author, genre) values ('Над пропастью во ржи', 'Джером Селинджер', 'NOVEL');
insert into Book (title, author, genre) values ('День опричника', 'Владимир Сорокин', 'FANTASY');
insert into Book (title, author, genre) values ('Тайные виды на гору Фудзи', 'Владимир Пелевин', 'NOVEL');
insert into Book (title, author, genre) values ('Философия Java', 'Брюс Эккель', 'SCIENCE');
insert into Book (title, author, genre) values ('Психопатология обыденной жизни', 'Фрейд Зигмунд', 'PSYCHOLOGY');
insert into Book (title, author, genre) values ('Игра в бисер', 'Герман Гессе', 'NOVEL');
insert into Book (title, author, genre) values ('Бытие и время', 'Мартин Хайдеггер', 'PHILOSOPHY');
insert into Book (title, author, genre) values ('Мастер и Маргарита', 'Михаил Булгаков', 'NOVEL');
insert into Book (title, author, genre) values ('Горе от ума', 'Александр Грибоедов', 'SATIRE');
insert into Book (title, author, genre) values ('Тихий Дон', 'Михаил Шолохов', 'NOVEL');
insert into Book (title, author, genre) values ('Гарри Поттер', 'Джоан Роулинг', 'FANTASY');
insert into Book (title, author, genre) values ('Мы начинаем в конце', 'Уитакер Крис', 'DETECTIVE');
insert into Book (title, author, genre) values ('Щегол', 'Донна Тартт', 'NOVEL');
insert into Book (title, author, genre) values ('Великий Гэтсби', 'Фрэнсис Фицджеральд', 'CLASSIC');
insert into Book (title, author, genre) values ('Думай и богатей', 'Наполеон Хилл', 'PSYCHOLOGY');
insert into Book (title, author, genre) values ('Унесенные ветром', 'Маргарет Митчелл', 'CLASSIC');
insert into Book (title, author, genre) values ('Сумерки. Сага', 'Стефани Майер', 'SAGA');
insert into Book (title, author, genre) values ('Код да Винчи', 'Дэн Браун', 'CLASSIC');
insert into Book (title, author, genre) values ('Алхимик', 'Пауло Коэльо', 'NOVEL');
insert into Book (title, author, genre) values ('Властелин колец', 'Дж. Р. Р. Толкин', 'FANTASY');
insert into Book (title, author, genre) values ('Библия', '-', 'RELIGIOUS');
insert into Book (title, author, genre) values ('Лолита', 'Владимир Набоков', 'NOVEL');
insert into Book (title, author, genre) values ('Десять негритят', 'Агата Кристи', 'DETECTIVE');
insert into Book (title, author, genre) values ('Повесть о двух городах', 'Чарльз Диккенс', 'NOVEL');
insert into Book (title, author, genre) values ('Алиса в стране чудес', 'Льюис Кэрролл', 'CHILDREN');
insert into Book (title, author, genre) values ('Сын Гора', 'Владислав Лесков', 'HISTORY');
insert into Book (title, author, genre) values ('Итальянская кампания', 'Бонапарт Наполеон', 'HISTORY');
insert into Book (title, author, genre) values ('Потерянное царство', 'Сергей Плохий', 'HISTORY');
insert into Book (title, author, genre) values ('Персидские войны', 'Михаил Куторга', 'HISTORY');
insert into Book (title, author, genre) values ('Бурквиль', 'Галина Бабурова', 'CHILDREN');
insert into Book (title, author, genre) values ('История о настоящей дружбе', 'Анна Купырина', 'CHILDREN');
insert into Book (title, author, genre) values ('Приграничное владение', 'Артём матюшенко', 'THRILLER');
insert into Book (title, author, genre) values ('Третий', 'Евгения Калько', 'THRILLER');
insert into Book (title, author, genre) values ('Деловая этика', 'Ирина Иванова', 'BUSINESS');
insert into Book (title, author, genre) values ('Учёт и Анализ', 'Дмитрий Хавин', 'BUSINESS');